# The name of our workflow
name: Build

on:
# Trigger the workflow on push or pull request,
# but only for the main branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - name: Build App
        run: bash ./gradlew --no-daemon clean assembleRelease
      - name: Artifact
        uses: actions/upload-artifact@v2
        with:
          name: kricheditor.zip
          path: app/build/outputs/apk

