# The name of our workflow
name: Build

on:
# Trigger the workflow on push or pull request,
# but only for the main branch
  push:
    branches:
      - master
  pull_request:
    push:
      branches:
        - master

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build the app
        run: ./gradlew build
      - name: Build
        run: bash ./gradlew assembleRelease
      - name: Artifact
        uses: actions/upload-artifact@v2
        with:
          name: kricheditor.zip
          path: app/build/outputs/apk

